# file generated by: chef generate attribute default

# By convention, when attributes are set in a cookbook’s attribute file, the values are expected to be namespaced under a top-level key matching the cookbook name
default['motd-attributes']['company'] = 'Chef'
